# Generated by Django 4.2.3 on 2023-08-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wantedlist_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fname", models.CharField(max_length=30)),
                ("Lname", models.CharField(max_length=30)),
                ("Email", models.CharField(max_length=30)),
                ("Password", models.CharField(max_length=30)),
            ],
        ),
    ]
