# Generated by Django 4.2.4 on 2023-08-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wantedlist_app', '0003_rename_password_login_password_login_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Password',
        ),
    ]
