# Generated by Django 4.2.4 on 2023-09-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wantedlist_app', '0007_show_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='image',
            new_name='images',
        ),
    ]
