# Generated by Django 4.2.4 on 2023-09-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wantedlist_app', '0009_rename_images_show_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=30)),
                ('Lname', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='show',
            name='Images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
