# Generated by Django 4.2.4 on 2023-09-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wantedlist_app', '0010_contact_alter_show_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Message',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
