# Generated by Django 4.2.4 on 2023-09-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wantedlist_app', '0006_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/'),
        ),
    ]
