# Generated by Django 4.2.4 on 2023-09-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wantedlist_app', '0008_rename_image_show_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='images',
            new_name='Images',
        ),
    ]
